% Make plots of Ahlstrom regional GPP/NEE response to EP/CP ENSO

% Parameters
wdth = 0.25;
offs = 0.15;
scale = 0.001;
clr = [103,0,31
    178,24,43
    214,96,77
    244,165,130
    253,219,199
    224,224,224
    186,186,186
    135,135,135
    77,77,77
    26,26,26]/255;

h = figure('Color','w');
h.Units = 'inches';
h.Position = [1 1 7 4];

plot([0 6], [0 0], 'k-')
hold on;

%% MsTMIP
load ./data/cp_ep_gpp_mstmip_regional.mat;

% Ensemble
b1 = dberg_box(1-offs,CP_GPP_tropical_annual_beta*scale,clr(2,:),'w',wdth);
dberg_box(2-offs,CP_GPP_semiarid_annual_beta*scale,clr(2,:),'w',wdth);
dberg_box(4-offs,CP_GPP_grass_annual_beta*scale,clr(2,:),'w',wdth);
dberg_box(3-offs,CP_GPP_extratropical_annual_beta*scale,clr(2,:),'w',wdth);
dberg_box(5-offs,CP_GPP_tundra_annual_beta*scale,clr(2,:),'w',wdth);

b2 = dberg_box(1+offs,EP_GPP_tropical_annual_beta*scale,clr(10,:),'w',wdth);
dberg_box(2+offs,EP_GPP_semiarid_annual_beta*scale,clr(10,:),'w',wdth);
dberg_box(4+offs,EP_GPP_grass_annual_beta*scale,clr(10,:),'w',wdth);
dberg_box(3+offs,EP_GPP_extratropical_annual_beta*scale,clr(10,:),'w',wdth);
dberg_box(5+offs,EP_GPP_tundra_annual_beta*scale,clr(10,:),'w',wdth);

% Means and CIs
plot([1-offs 1-offs],...
    [CP_GPP_tropical_annual_mean_beta(1)-CP_GPP_tropical_annual_mean_beta_CI(1) CP_GPP_tropical_annual_mean_beta(1)+CP_GPP_tropical_annual_mean_beta_CI(1)]/1000,...
    '-','Color',clr(4,:));
plot([2-offs 2-offs],...
    [CP_GPP_semiarid_annual_mean_beta(1)-CP_GPP_semiarid_annual_mean_beta_CI(1) CP_GPP_semiarid_annual_mean_beta(1)+CP_GPP_semiarid_annual_mean_beta_CI(1)]/1000,...
    '-','Color',clr(4,:));
plot([4-offs 4-offs],...
    [CP_GPP_grass_annual_mean_beta(1)-CP_GPP_grass_annual_mean_beta_CI(1) CP_GPP_grass_annual_mean_beta(1)+CP_GPP_grass_annual_mean_beta_CI(1)]/1000,...
    '-','Color',clr(4,:));
plot([3-offs 3-offs],...
    [CP_GPP_extratropical_annual_mean_beta(1)-CP_GPP_extratropical_annual_mean_beta_CI(1) CP_GPP_extratropical_annual_mean_beta(1)+CP_GPP_extratropical_annual_mean_beta_CI(1)]/1000,...
    '-','Color',clr(4,:));
plot([5-offs 5-offs],...
    [CP_GPP_tundra_annual_mean_beta(1)-CP_GPP_tundra_annual_mean_beta_CI(1) CP_GPP_tundra_annual_mean_beta(1)+CP_GPP_tundra_annual_mean_beta_CI(1)]/1000,...
    '-','Color',clr(4,:));

plot([1+offs 1+offs],...
    [EP_GPP_tropical_annual_mean_beta(1)-EP_GPP_tropical_annual_mean_beta_CI(1) EP_GPP_tropical_annual_mean_beta(1)+EP_GPP_tropical_annual_mean_beta_CI(1)]/1000,...
    '-','Color',clr(8,:));
plot([2+offs 2+offs],...
    [EP_GPP_semiarid_annual_mean_beta(1)-EP_GPP_semiarid_annual_mean_beta_CI(1) EP_GPP_semiarid_annual_mean_beta(1)+EP_GPP_semiarid_annual_mean_beta_CI(1)]/1000,...
    '-','Color',clr(8,:));
plot([4+offs 4+offs],...
    [EP_GPP_grass_annual_mean_beta(1)-EP_GPP_grass_annual_mean_beta_CI(1) EP_GPP_grass_annual_mean_beta(1)+EP_GPP_grass_annual_mean_beta_CI(1)]/1000,...
    '-','Color',clr(8,:));
plot([3+offs 3+offs],...
    [EP_GPP_extratropical_annual_mean_beta(1)-EP_GPP_extratropical_annual_mean_beta_CI(1) EP_GPP_extratropical_annual_mean_beta(1)+EP_GPP_extratropical_annual_mean_beta_CI(1)]/1000,...
    '-','Color',clr(8,:));
plot([5+offs 5+offs],...
    [EP_GPP_tundra_annual_mean_beta(1)-EP_GPP_tundra_annual_mean_beta_CI(1) EP_GPP_tundra_annual_mean_beta(1)+EP_GPP_tundra_annual_mean_beta_CI(1)]/1000,...
    '-','Color',clr(8,:));

plot(1-offs,CP_GPP_tropical_annual_mean_beta*scale,'^','Color',clr(4,:));
plot(2-offs,CP_GPP_semiarid_annual_mean_beta*scale,'^','Color',clr(4,:));
plot(4-offs,CP_GPP_grass_annual_mean_beta*scale,'^','Color',clr(4,:));
plot(3-offs,CP_GPP_extratropical_annual_mean_beta*scale,'^','Color',clr(4,:));
plot(5-offs,CP_GPP_tundra_annual_mean_beta*scale,'^','Color',clr(4,:));

plot(1+offs,EP_GPP_tropical_annual_mean_beta*scale,'^','Color',clr(8,:));
plot(2+offs,EP_GPP_semiarid_annual_mean_beta*scale,'^','Color',clr(8,:));
plot(4+offs,EP_GPP_grass_annual_mean_beta*scale,'^','Color',clr(8,:));
plot(3+offs,EP_GPP_extratropical_annual_mean_beta*scale,'^','Color',clr(8,:));
plot(5+offs,EP_GPP_tundra_annual_mean_beta*scale,'^','Color',clr(8,:));

%% LUE
clear CP* EP* ep_* cp_* models;
load ./data/cp_ep_gpp_lue_regional.mat;

% CCW
plot([1-offs+offs/2 1-offs+offs/2],...
    [CP_GPP_tropical_annual_beta(1)-CP_GPP_tropical_annual_beta_CI(1) CP_GPP_tropical_annual_beta(1)+CP_GPP_tropical_annual_beta_CI(1)]/1000,...
    '-','Color',clr(4,:));
plot([2-offs+offs/2 2-offs+offs/2],...
    [CP_GPP_semiarid_annual_beta(1)-CP_GPP_semiarid_annual_beta_CI(1) CP_GPP_semiarid_annual_beta(1)+CP_GPP_semiarid_annual_beta_CI(1)]/1000,...
    '-','Color',clr(4,:));
plot([4-offs+offs/2 4-offs+offs/2],...
    [CP_GPP_grass_annual_beta(1)-CP_GPP_grass_annual_beta_CI(1) CP_GPP_grass_annual_beta(1)+CP_GPP_grass_annual_beta_CI(1)]/1000,...
    '-','Color',clr(4,:));
plot([3-offs+offs/2 3-offs+offs/2],...
    [CP_GPP_extratropical_annual_beta(1)-CP_GPP_extratropical_annual_beta_CI(1) CP_GPP_extratropical_annual_beta(1)+CP_GPP_extratropical_annual_beta_CI(1)]/1000,...
    '-','Color',clr(4,:));
plot([5-offs+offs/2 5-offs+offs/2],...
    [CP_GPP_tundra_annual_beta(1)-CP_GPP_tundra_annual_beta_CI(1) CP_GPP_tundra_annual_beta(1)+CP_GPP_tundra_annual_beta_CI(1)]/1000,...
    '-','Color',clr(4,:));

plot([1+offs+offs/2 1+offs+offs/2],...
    [EP_GPP_tropical_annual_beta(1)-EP_GPP_tropical_annual_beta_CI(1) EP_GPP_tropical_annual_beta(1)+EP_GPP_tropical_annual_beta_CI(1)]/1000,...
    '-','Color',clr(8,:));
plot([2+offs+offs/2 2+offs+offs/2],...
    [EP_GPP_semiarid_annual_beta(1)-EP_GPP_semiarid_annual_beta_CI(1) EP_GPP_semiarid_annual_beta(1)+EP_GPP_semiarid_annual_beta_CI(1)]/1000,...
    '-','Color',clr(8,:));
plot([4+offs+offs/2 4+offs+offs/2],...
    [EP_GPP_grass_annual_beta(1)-EP_GPP_grass_annual_beta_CI(1) EP_GPP_grass_annual_beta(1)+EP_GPP_grass_annual_beta_CI(1)]/1000,...
    '-','Color',clr(8,:));
plot([3+offs+offs/2 3+offs+offs/2],...
    [EP_GPP_extratropical_annual_beta(1)-EP_GPP_extratropical_annual_beta_CI(1) EP_GPP_extratropical_annual_beta(1)+EP_GPP_extratropical_annual_beta_CI(1)]/1000,...
    '-','Color',clr(8,:));
plot([5+offs+offs/2 5+offs+offs/2],...
    [EP_GPP_tundra_annual_beta(1)-EP_GPP_tundra_annual_beta_CI(1) EP_GPP_tundra_annual_beta(1)+EP_GPP_tundra_annual_beta_CI(1)]/1000,...
    '-','Color',clr(8,:));

plot(1-offs+offs/2,CP_GPP_tropical_annual_beta(1)*scale,'x','Color',clr(4,:));
plot(2-offs+offs/2,CP_GPP_semiarid_annual_beta(1)*scale,'x','Color',clr(4,:));
plot(4-offs+offs/2,CP_GPP_grass_annual_beta(1)*scale,'x','Color',clr(4,:));
plot(3-offs+offs/2,CP_GPP_extratropical_annual_beta(1)*scale,'x','Color',clr(4,:));
plot(5-offs+offs/2,CP_GPP_tundra_annual_beta(1)*scale,'x','Color',clr(4,:));

plot(1+offs+offs/2,EP_GPP_tropical_annual_beta(1)*scale,'x','Color',clr(8,:));
plot(2+offs+offs/2,EP_GPP_semiarid_annual_beta(1)*scale,'x','Color',clr(8,:));
plot(4+offs+offs/2,EP_GPP_grass_annual_beta(1)*scale,'x','Color',clr(8,:));
plot(3+offs+offs/2,EP_GPP_extratropical_annual_beta(1)*scale,'x','Color',clr(8,:));
plot(5+offs+offs/2,EP_GPP_tundra_annual_beta(1)*scale,'x','Color',clr(8,:));

% MOD17
plot([1-offs-offs/2 1-offs-offs/2],...
    [CP_GPP_tropical_annual_beta(2)-CP_GPP_tropical_annual_beta_CI(2) CP_GPP_tropical_annual_beta(2)+CP_GPP_tropical_annual_beta_CI(2)]/1000,...
    '-','Color',clr(4,:));
plot([2-offs-offs/2 2-offs-offs/2],...
    [CP_GPP_semiarid_annual_beta(2)-CP_GPP_semiarid_annual_beta_CI(2) CP_GPP_semiarid_annual_beta(2)+CP_GPP_semiarid_annual_beta_CI(2)]/1000,...
    '-','Color',clr(4,:));
plot([4-offs-offs/2 4-offs-offs/2],...
    [CP_GPP_grass_annual_beta(2)-CP_GPP_grass_annual_beta_CI(2) CP_GPP_grass_annual_beta(2)+CP_GPP_grass_annual_beta_CI(2)]/1000,...
    '-','Color',clr(4,:));
plot([3-offs-offs/2 3-offs-offs/2],...
    [CP_GPP_extratropical_annual_beta(2)-CP_GPP_extratropical_annual_beta_CI(2) CP_GPP_extratropical_annual_beta(2)+CP_GPP_extratropical_annual_beta_CI(2)]/1000,...
    '-','Color',clr(4,:));
plot([5-offs-offs/2 5-offs-offs/2],...
    [CP_GPP_tundra_annual_beta(2)-CP_GPP_tundra_annual_beta_CI(2) CP_GPP_tundra_annual_beta(2)+CP_GPP_tundra_annual_beta_CI(2)]/1000,...
    '-','Color',clr(4,:));

plot([1+offs-offs/2 1+offs-offs/2],...
    [EP_GPP_tropical_annual_beta(2)-EP_GPP_tropical_annual_beta_CI(2) EP_GPP_tropical_annual_beta(2)+EP_GPP_tropical_annual_beta_CI(2)]/1000,...
    '-','Color',clr(8,:));
plot([2+offs-offs/2 2+offs-offs/2],...
    [EP_GPP_semiarid_annual_beta(2)-EP_GPP_semiarid_annual_beta_CI(2) EP_GPP_semiarid_annual_beta(2)+EP_GPP_semiarid_annual_beta_CI(2)]/1000,...
    '-','Color',clr(8,:));
plot([4+offs-offs/2 4+offs-offs/2],...
    [EP_GPP_grass_annual_beta(2)-EP_GPP_grass_annual_beta_CI(2) EP_GPP_grass_annual_beta(2)+EP_GPP_grass_annual_beta_CI(2)]/1000,...
    '-','Color',clr(8,:));
plot([3+offs-offs/2 3+offs-offs/2],...
    [EP_GPP_extratropical_annual_beta(2)-EP_GPP_extratropical_annual_beta_CI(2) EP_GPP_extratropical_annual_beta(2)+EP_GPP_extratropical_annual_beta_CI(2)]/1000,...
    '-','Color',clr(8,:));
plot([5+offs-offs/2 5+offs-offs/2],...
    [EP_GPP_tundra_annual_beta(2)-EP_GPP_tundra_annual_beta_CI(2) EP_GPP_tundra_annual_beta(2)+EP_GPP_tundra_annual_beta_CI(2)]/1000,...
    '-','Color',clr(8,:));

plot(1-offs-offs/2,CP_GPP_tropical_annual_beta(2)*scale,'s','Color',clr(4,:));
plot(2-offs-offs/2,CP_GPP_semiarid_annual_beta(2)*scale,'s','Color',clr(4,:));
plot(4-offs-offs/2,CP_GPP_grass_annual_beta(2)*scale,'s','Color',clr(4,:));
plot(3-offs-offs/2,CP_GPP_extratropical_annual_beta(2)*scale,'s','Color',clr(4,:));
plot(5-offs-offs/2,CP_GPP_tundra_annual_beta(2)*scale,'s','Color',clr(4,:));

plot(1+offs-offs/2,EP_GPP_tropical_annual_beta(2)*scale,'s','Color',clr(8,:));
plot(2+offs-offs/2,EP_GPP_semiarid_annual_beta(2)*scale,'s','Color',clr(8,:));
plot(4+offs-offs/2,EP_GPP_grass_annual_beta(2)*scale,'s','Color',clr(8,:));
plot(3+offs-offs/2,EP_GPP_extratropical_annual_beta(2)*scale,'s','Color',clr(8,:));
plot(5+offs-offs/2,EP_GPP_tundra_annual_beta(2)*scale,'s','Color',clr(8,:));


set(gca, 'XLim',[0.5 5.5], 'XTick',1:5, 'TickDir','out',...
    'TickLength',[0.02 0.04], 'XTickLabels',{'Tropical Forest','Semiarid',...
    'Extratropical Forest','Grass/Crop','Tundra/Arctic Shrub'})
box off;

ylabel('GPP response (Pg C yr^{-1} SD^{-1})')

plot(4.8, -0.3, 'ks');
text(4.9, -0.3, 'MOD17', 'HorizontalAlignment','left', 'VerticalAlignment','middle', 'FontSize',9)
plot(4.8, -0.36, 'k^');
text(4.9, -0.36, 'MsTMIP', 'HorizontalAlignment','left', 'VerticalAlignment','middle', 'FontSize',9)
plot(4.8, -0.42, 'kx');
text(4.9, -0.42, 'CCW', 'HorizontalAlignment','left', 'VerticalAlignment','middle', 'FontSize',9)

legend([b1 b2], 'CP','EP', 'Location','southeast', 'FontSize',9);
legend('boxoff');

set(gcf,'PaperPositionMode','auto')
print('-dtiff','-f1','-r300','./output/epi-cpi-gpp-byAhlstromRegion.tif')
close all;

